name: Docker Nightly

on:
  schedule:
    - cron: "0 2 * * *"  # 02:00 UTC nightly
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed for GHCR push
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
      DATE_TAG: ${{ github.run_id }} # fallback; we’ll compute yyyyMMdd below
    steps:
      - uses: actions/checkout@v4

      - name: Compute date tag
        id: date
        run: echo "yyyymmdd=$(date -u +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:nightly
            ${{ env.IMAGE_NAME }}:nightly-${{ steps.date.outputs.yyyymmdd }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
