name: Nightly E2E

on:
  schedule:
    - cron: "0 2 * * *" # 02:00 UTC nightly
  workflow_dispatch: {}

concurrency:
  group: nightly-e2e
  cancel-in-progress: false

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      HF_HOME: ${{ github.workspace }}/.hf_home        # new preferred cache root
      TRANSFORMERS_CACHE: ${{ github.workspace }}/.hf_home/hub  # backward compat if libs still read it

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Cache HF models
        uses: actions/cache@v4
        with:
          path: ${{ env.HF_HOME }}
          key: hf-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Install package (src layout)
        run: |
          pip install -e .

      - name: Run E2E tests
        run: pytest -m "e2e" -q
