name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.11" ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller huggingface_hub

      # If you want to vendor a model for offline binaries, uncomment:
      # - name: Download model to models/email-spam
      #   run: |
      #     python - <<'PY'
      #     from huggingface_hub import snapshot_download
      #     snapshot_download('mrm8488/bert-tiny-finetuned-sms-spam-detection',
      #                       local_dir='models/email-spam',
      #                       local_dir_use_symlinks=False)
      #     PY

      - name: Build binary with PyInstaller
        shell: bash
        run: |
          pyinstaller --onefile spam_bert.py
          ls -al dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spam-bert-${{ runner.os }}
          path: dist/*

  create-release:
    needs: build-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: spam-bert-*
          path: ./artifacts
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
