name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write   # needed for GHCR push

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        python-version: [ "3.11" ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install -e .

      - name: Build binary with PyInstaller
        run: |
          pyinstaller --onefile src/spam_bert/app.py --name spam-bert
          python -c "import glob; print('Built:', glob.glob('dist/*'))"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spam-bert-${{ runner.os }}
          path: |
            dist/spam-bert.exe
            dist/spam-bert
          if-no-files-found: ignore

  docker:
    runs-on: ubuntu-latest
    needs: build-binaries
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: meta
        run: |
          ref="${GITHUB_REF##*/}"           # e.g. v1.2.3
          echo "version=${ref}" >> $GITHUB_OUTPUT
          echo "version_no_v=${ref#v}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
            ${{ env.IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.title=Spam BERT Detector
            org.opencontainers.image.description=BERT-powered spam/ham classifier (CLI + REST API)
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-release:
    needs: [build-binaries, docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: spam-bert-*
          path: ./artifacts
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
